name: "e2e tests"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths-ignore:
      - "browser_patches/**"
      - "docs/**"
    types: [labeled]
    branches:
      - main
      - release-*

jobs:
  test_linux:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i -g npm@8
      - run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run build
      - run: npx playwright install --with-deps ${{ matrix.browser }} chromium
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test -- --project=${{ matrix.browser }}
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.browser }}-${{ matrix.os }}-test-results
          path: test-results
